from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


DISCLAIMER_TEXT = (
    "This report is generated by an AI clinical decision support system for educational "
    "and research purposes only. It must not be used as a substitute for professional "
    "medical advice, diagnosis, or treatment. Always consult a qualified healthcare "
    "provider for medical decisions."
)


class HealthStatus(BaseModel):
    status: Literal["ok", "degraded"] = "ok"
    ollama: bool
    chromadb: bool
    message: str | None = None


class ModelStatus(BaseModel):
    llama3: bool = False
    llava: bool = False
    whisper: bool = False
    chromadb: bool = False


class VisionFindings(BaseModel):
    image_type: str = "unknown"
    findings: list[str] = Field(default_factory=list)
    anomalies: list[str] = Field(default_factory=list)
    normal_structures: list[str] = Field(default_factory=list)
    severity_hint: str = "normal"
    confidence: float = 0.0
    analysis_notes: str = ""


class LabPatientInfo(BaseModel):
    name: str | None = None
    age: str | None = None
    gender: str | None = None
    date: str | None = None


class LabTestResult(BaseModel):
    test_name: str
    value: str
    reference_range: str | None = None
    flag: str | None = None


class LabReport(BaseModel):
    report_type: str = "Unknown"
    patient_info: LabPatientInfo = Field(default_factory=LabPatientInfo)
    test_results: list[LabTestResult] = Field(default_factory=list)
    clinical_summary: str = ""
    critical_values: list[str] = Field(default_factory=list)


class SourceReference(BaseModel):
    title: str
    pmid: str | None = None
    url: str | None = None


class RelevantCondition(BaseModel):
    condition: str
    likelihood: str
    supporting_symptoms: list[str] = Field(default_factory=list)
    supporting_evidence_indices: list[int] = Field(default_factory=list)


class RAGContext(BaseModel):
    relevant_conditions: list[RelevantCondition] = Field(default_factory=list)
    supporting_evidence: list[str] = Field(default_factory=list)
    sources: list[SourceReference] = Field(default_factory=list)
    retrieval_count: int = 0
    key_clinical_patterns: list[str] = Field(default_factory=list)
    missing_information: list[str] = Field(default_factory=list)


class DifferentialDiagnosis(BaseModel):
    rank: int
    condition: str
    icd_10_code: str
    confidence_score: float
    supporting_findings: list[str] = Field(default_factory=list)
    against_findings: list[str] = Field(default_factory=list)
    clinical_rationale: str = ""


class ClinicalReport(BaseModel):
    patient_summary: str
    differential_diagnosis: list[DifferentialDiagnosis] = Field(default_factory=list)
    red_flags: list[str] = Field(default_factory=list)
    recommended_next_steps: list[str] = Field(default_factory=list)
    estimated_urgency: Literal["immediate", "urgent", "semi_urgent", "routine"]
    additional_history_needed: list[str] = Field(default_factory=list)
    disclaimer: str = DISCLAIMER_TEXT
